f1 = figure('visible','on');
i=floor(random('unif',1,1269));
plot(master(:,i),'k-'); 
hold on;
plot(completed_copy(:,i),'m-');
hold on;
plot(completed_copy(:,i+1269),'m-'); 
hold on;
plot(completed_copy(:,i+2538),'m-');
hold on;
plot(completed_copy(:,i+3807),'m-'); 
hold on;
plot(completed_copy(:,i+5076),'m-');
hold on;
